name: Run Log Collection Script

on:
  schedule:
    - cron: '0 8 * * *' # Executa todo dia às 08:00 (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run coletar_logs.py
      run: python coletar_logs.py

    - name: Upload eventos_seguranca.csv
      uses: actions/upload-artifact@v3
      with:
        name: eventos-seguranca
        path: eventos_seguranca.csv
